# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolution function for clock-reset models
#' 
#' @description Internal function of 
#' \code{probtrans_by_convolution_clockreset}. It is written in C++
#' and is not meant to be called
#' directly by the user.
#' 
#' @param time_vector,integrand_1,integrand_2 Numeric vectors.
#' @author Moritz Gerstung & Rui Costa
#' @seealso \code{\link{probtrans_by_convolution_clockreset}}.
convolute_clockreset <- function(time_vector, integrand_1, integrand_2) {
    .Call(`_ebmstate_convolute_clockreset`, time_vector, integrand_1, integrand_2)
}

#' Convolution function for clock-forward models
#' 
#' @description Internal function of 
#' \code{probtrans_by_convolution_clockforward}. It is written in C++ and is
#'  not meant to be called
#' directly by the user.
#' 
#' @param time_vector,diff_vector,probtrans_vector_1,probtrans_vector_2 Numeric vectors.
#' @author Moritz Gerstung & Rui Costa
#' @seealso \code{\link{probtrans_by_convolution_clockforward}}.
convolute_clockforward <- function(time_vector, diff_vector, probtrans_vector_1, probtrans_vector_2) {
    .Call(`_ebmstate_convolute_clockforward`, time_vector, diff_vector, probtrans_vector_1, probtrans_vector_2)
}

